### ISSUE TITLE
error using external module - progressbar

### ISSUE THREAD

**Issue by samkhan13** [erget/StereoVision#2] opened 2015-03-11 10:08 UTC
while running capture_chessboards from the terminal an ImportError was raised about `progressbar`. it can help to indicate to users in the README.rst that they will need to pip install the module. this was only a minor issue.

**Comment by samkhan13** [comment] 2015-03-11 10:24
there were some more issues while using `progressbar` I have version 2.3 and I got this error: 
```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/capture_chessboards", line 84, in <module>
    main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/capture_chessboards", line 72, in main
    progress.update(progress.maxval - (args.num_pictures - i))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/progressbar/__init__.py", line 276, in update
    if not self._need_update(): return
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/progressbar/__init__.py", line 251, in _need_update
    if self.currval >= self.next_update or self.finished: return True
AttributeError: next_update
```
I wasn't able to figure out what to do about it so I have merely commented out the lines of code related to progress bar in `capture_chessboards` for my current use.

**Comment by samkhan13** [comment] 2015-03-11 10:34
same *AttributeError* related to `progressbar` while using `calibrate_cameras`:
```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/calibrate_cameras", line 56, in <module>
    main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/calibrate_cameras", line 52, in main
    calibrate_folder(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/stereovision/ui_utils.py", line 105, in calibrate_folder
    progress.update(progress.maxval - len(args.input_files))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/progressbar/__init__.py", line 276, in update
    if not self._need_update(): return
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/progressbar/__init__.py", line 251, in _need_update
    if self.currval >= self.next_update or self.finished: return True
AttributeError: next_update
```

**Comment by erget** [comment] 2015-03-11 19:22
Hi @samkhan13 ,
Thanks for reporting this issue. ``progressbar`` is noted, however, in the ``requires`` argument in ``setup.py``. AFAIK that dependency should install correctly if you use ``pip`` to install the package - did you use ``pip`` or did you install it by hand?

Right now I'm traveling for work but if you have the time I'd like to troubleshoot this a bit with you until I can fix it when I get back (among other things I don't currently have a stereo rig so testing is a bit difficult for me at the moment). 

``progressbar``'s last release was this year, so it could be that there was an update that broke client code since then, but that would honestly surprise me a lot. I definitely can confirm that the code functioned using ``progressbar`` in the past. Unfortunately my Internet here is really slow, but I expect that if this issue is really from ``progressbar`` that there will be other reporters out there. Are you aware of any such issues?

**Comment by erget** [comment] 2015-03-11 19:26
One more note, I just tried installing ``progressbar`` with ``pip`` (I'm working on a fairly fresh install here and hadn't had it installed). The install failed with the following log output:

```
Downloading/unpacking progressbar
  Getting page https://pypi.python.org/simple/progressbar/
  URLs to search for versions for progressbar:
  * https://pypi.python.org/simple/progressbar/
  Analyzing links from page https://pypi.python.org/simple/progressbar/
    Found link https://pypi.python.org/packages/source/p/progressbar/progressbar-2.1.tar.gz#md5=a51d18b04fc752df66ea5aec7abb917f (from https://pypi.python.org/simple/progressbar/), version: 2.1
    Found link https://pypi.python.org/packages/source/p/progressbar/progressbar-2.2.tar.gz#md5=8ea4e2c17a8ec9e7d153767c5f2a7b28 (from https://pypi.python.org/simple/progressbar/), version: 2.2
    Found link https://pypi.python.org/packages/source/p/progressbar/progressbar-2.3.tar.gz#md5=cb6359e54edbb5a1ede42f2b3da5fd75 (from https://pypi.python.org/simple/progressbar/), version: 2.3
    Skipping link http://code.google.com/p/python-progressbar (from https://pypi.python.org/simple/progressbar/); not a file
    Skipping link http://code.google.com/p/python-progressbar/ (from https://pypi.python.org/simple/progressbar/); not a file
    Skipping link http://code.google.com/p/python-progressbar/source/browse/progressbar/examples.py (from https://pypi.python.org/simple/progressbar/); unknown archive format: .py
  Not searching http://code.google.com/p/python-progressbar (from https://pypi.python.org/simple/progressbar/) for files because external urls are disallowed.
  Not searching http://code.google.com/p/python-progressbar (from https://pypi.python.org/simple/progressbar/) for files because external urls are disallowed.
  Not searching http://code.google.com/p/python-progressbar/ (from https://pypi.python.org/simple/progressbar/) for files because external urls are disallowed.
  Not searching http://code.google.com/p/python-progressbar/ (from https://pypi.python.org/simple/progressbar/) for files because external urls are disallowed.
  Using version 2.3 (newest of versions: 2.3, 2.2, 2.1)
  Downloading progressbar-2.3.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/p/progressbar/progressbar-2.3.tar.gz#md5=cb6359e54edbb5a1ede42f2b3da5fd75 (from https://pypi.python.org/simple/progressbar/)
  Running setup.py (path:/tmp/pip_build_root/progressbar/setup.py) egg_info for package progressbar
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/tmp/pip_build_root/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/tmp/pip_build_root/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/usr/lib64/python3.4/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/progressbar/setup.py", line 5, in <module>

    import progressbar

  File "/tmp/pip_build_root/progressbar/progressbar/__init__.py", line 59, in <module>

    from progressbar.widgets import *

  File "/tmp/pip_build_root/progressbar/progressbar/widgets.py", line 121, in <module>

    class FileTransferSpeed(Widget):

  File "/usr/lib64/python3.4/abc.py", line 133, in __new__

    cls = super().__new__(mcls, name, bases, namespace)

ValueError: 'format' in __slots__ conflicts with class variable

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/progressbar
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3.4/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3.4/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3.4/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/progressbar
```

So it looks like the installation of ``progressbar`` has, at least on my platform, become non-trivial - before it worked like a charm. Did you encounter similar problems?

**Comment by samkhan13** [comment] 2015-03-12 06:02
i did use `pip install StereoVision` and i was very happy to see it get installed without errors. i do see that the `requires

**Comment by erget** [comment] 2015-03-16 12:18
Thanks again for the feedback and I'm glad you like the code! I've been traveling the past few days, but I did see that you uploaded some pictures that I can run my own tests with so I hope to have investigated this a little better by the end of the week. I'm assuming that something has changed on the API of ``progressbar``, but before testing I can't confirm that at all. Just wanted to give a heads up why it's taken so long for me to get back to you.

**Comment by samkhan13** [comment] 2015-03-16 13:24
no problem at all daniel. this wasn't a critical issue, merely commenting out the part for progressbar got the rest of the code working. i did upload pictures but those ones turned out to be faulty because there was a computer screen in the background of the chess board which caught reflection from my window. the reflection looks like a brighter chess board because of checkered grill on the window. the rectified images created due to the calibration run using those images turned out to be bad. i then took another set of pictures. this time the rectified images seem good. i will upload new ones to that folder now. i haven't got to tuning the block matcher yet. i will put my experiment into a repo. thanks again for everything.

**Comment by erget** [comment] 2015-03-21 12:18
Hi Sam,

I figured out what the problem was. Apparently there was a change in the library ``progressbar`` which invalidated my old code - it might be that the old code was actually only functional because of a bug, because it looks like the developer of ``progressbar`` may have always intended for the library to be used that way. There's a commit coming at you that will have fixed that problem. I would ask you to pull that branch, install it and see if you can confirm that the problem has also been fixed on your end. If you can, I'll merge that into ``master`` and push the whole thing as a new version to ``PyPI``, so you can either stick with the new version or install it with ``pip`` or ``easy_install``.

I also find the error of <1 pixel very impressive, and I think it's not due to my code, as much as I'd love to take credit for it. The real reason, in my opinion, is that all of your calibration pictures are pretty much the same. I would suggest moving the camera back and forth so that you're photographing the calibration board from diffferent distances, as well as different angles. It looks like the board's taped to a wall, so try tilting the cameras so that they're looking at it from an angle, turning them on their side, etc. Although the forecasted error score will suffer, your point clouds will profit from having a more robust calibration. Also, it may or may not be necessary to take that many pictures - my suggestion would be to play around with it a little and see. There's also nothing wrong with using different calibration pictures taken during different sessions, so don't be afraid to pick out the best ones from different picture capture sessions and using them together. As long as the board and the stereo rig hasn't changed, that shouldn't be a problem.

**Comment by samkhan13** [comment] 2015-03-21 12:23
thank you very much daniel. i will certainly do so.

best
sam

composed on my phone. please excuse any typos.

**Comment by erget** [comment] 2015-03-28 14:31
Hi @samkhan13, have you been able to confirm the bug fix on your side? I'm confident that the problem is gone now, but I would feel better if I had a confirmation from you. If you can confirm it, I can roll out the fixed version and close this issue.

**Comment by samkhan13** [comment] 2015-04-02 15:40
@erget the progress bar shows up and is working as expected :+1:

**Comment by sherl0ck-** [comment] 2016-01-12 10:44
Hello @erget ! I just downloaded StereoVision with pip and Im facing the same progressbar issue as above. I also saw you made a commit in the master branch, which makes me confused to why the code is reporting the same error. Am I supposed to pull it via github or something along those lines?

**Comment by erget** [comment] 2016-01-12 18:03
Hi @sherl0ck- , Thanks for getting in touch with me about this. It looks like I forgot to merge this to master and thus have forgotten to push it out to PyPI. I'm on the run right now but I will double check and push you out a new version tomorrow. You're welcome to pull the project, of course, but this should work out of the box.

**Comment by sherl0ck-** [comment] 2016-01-14 11:02
Thanks for the quick response! Did you do it already and how do I go about updating the existing version?

**Closed** 2016-01-14 20:52 UTC

**Comment by erget** [comment] 2016-01-14 21:00
Hi there,

Sorry about that. I've pushed it back to PyPI and it should work now. Try installing it with:

    pip install -U StereoVision

That should update it to the newest release (1.0.2). Please let me know if it worked out :)

**Comment by sherl0ck-** [comment] 2016-01-15 05:30
Hi,

it did update to the new version, but the code terminates again for the same reason. Also tried rebooting and re-installation, just in case.

**Comment by erget** [comment] 2016-01-15 06:01
Okay. The one issue is that I had forgotten to merge onto master. I'm not
sure what the other one is. Can you send me the test data you're working
with and your traceback in the meantime? I can take a look at it on
Saturday and hopeful be able to duplicate the problem here.

**Comment by sherl0ck-** [comment] 2016-01-15 06:54
Thanks. Everything is on the link below.
https://drive.google.com/a/nyu.edu/folderview?id=0B6UVGh006mTeSVdqSmtGZW1tOWM&usp=sharing

**Comment by sdlouhy** [comment] 2018-05-24 02:13
If you really want to use the most current version (as of may 23, 2018) of progressbar, change the variable progressbar.maxval to progressbar.max_value.  they deprecated maxval in one of their more recent updates
